name: Run Pull

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: Run Pull
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH host to known hosts
      run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    - name: Clone Repository
      run: git clone https://github.com/MohitVerma007/mudita_server.git /var/www/mudita_server

    - name: Change Directory and Pull Updates
      run: |
        cd /var/www/mudita_server
        sudo git checkout main
        sudo git pull
