name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main  # Specify the main branch explicitly

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 62.72.31.25
          username: root
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/mudita_server
            ./.scripts/deploy.sh
          options: "-v"

